stages:
  - build
  - test

build:
  stage: build
  image: php:7.3-cli-stretch
  artifacts:
    paths:
      - ./

test:
  stage: test
  image: php:7.3-cli-stretch
  script:
    - bash ci/docker_install.sh
    - phpunit --testsuite One
