stages:
  - lint
  - self
  - build
  - test

lint:
  stage: lint
  image: sixlive/php-lint-fix

  script:
    - php-cs-fixer fix --dry-run

self:
  stage: self
  image: exakat/exakat

  script:
    - /usr/src/exakat/exakat.phar project -v

build:
  stage: build
  image: php:7.3-cli-stretch
  script:
    - bash ci/docker_install.sh

test:
  stage: test
  image: php:7.3-cli-stretch
  script:
    - sh ci/docker_install.sh
    - phpunit --testsuite One

