stages:
  - build
  - test

build:
  stage: build
  image: php:7.3-cli-stretch
  script:
    - bash ci/docker_install.sh

test:
  stage: test
  image: php:7.3-cli-stretch
  dependencies:
    - build
  script:
    - phpunit --testsuite One
