stages:
  - build
  - test

build:
  stage: build
  image: php:7.3-cli-stretch
  artifacts:
    paths:
      - ./
  script:
    - bash ci/docker_install.sh

test:
  stage: test
  image: php:7.3-cli-stretch
  dependencies: 
    - test
  script:
    - phpunit --testsuite One
